apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
    - configMapRef:
        name: nginx-configmap
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: config-volume
    configMap:
      name: nginx-configmap
      items:
      - key: index.html
        path: index.html
