apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: dGVzdDEyMw== # base64-encoded value of "test123"
