apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    {{- toYaml .Values.mysql.service.labels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
  selector:
    app: {{ .Values.mysql.deployment.labels.app }}
    tier: backend
  clusterIP: None
