apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: db-creds
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: db-creds
    secret:
      secretName: db-creds-secret
