apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  namespace: production
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
